### ISSUE TITLE
obb_generator_msgs cmake error

### ISSUE THREAD

**Issue by ParkJiil** [ChoiWooCheol/QT-LiDAR-Object-Detection#1]
I am interested in the LIDAR detection code. When I build your code, I get an error, maybe because 'obb_generator_msgs' is missing. I am wondering if you can commit the obb_generator_msgs source code. Thanks for your help!

**Comment by ChoiWooCheol** [comment]
i commit obb_generator_msgs file.

you should download obb_generator_msgs and build with other source codes

**Comment by ParkJiil** [comment]
Thanks for the quick answer. Sorry, but I have one more question. 'lidar_visionlab_clustering' error occurs when building up. This problem is also believed to be due to the lack of 'lidar_visionlab_clustering'. Can you commit this code too? I'm sorry to bother you.

fatal error: lidar_visionlab_clustering/cloudArray.h: No such file or directory
 #include <lidar_visionlab_clustering/cloudArray.h>

**Comment by ChoiWooCheol** [comment]
#include <lidar_visionlab_clustering/cloudArray.h>
this line must be change to 
#include <obb_generator_msgs/cloudArray.h>

**Comment by ChoiWooCheol** [comment]
I commit this issues

**Comment by ChoiWooCheol** [comment]
If you want to use this collected ROS package, I send latest version of this lidar detector to your e-mail.

**Comment by ChoiWooCheol** [comment]
And with '/points_raw' rosbag data. you want.

**Comment by ParkJiil** [comment]
Thanks for replying despite being busy. I will proceed with the changed content. 
And the ROS package you mentioned will be of great help to your research. 
I would appreciate it if you send it to me (e-mail address is tinz64@kaist.ac.kr).

**Comment by ParkJiil** [comment]
Also, I want to know if your code is dependent on Autoware. 
The following error occurs during the build-up process, but it seems that autoware needs to be installed.

No such file or directory
#include <op_ros_helpers/op_ROSHelpers.h>
#include <rtp/rtp_helper.h>

**Comment by ParkJiil** [comment]
I tried with the file you sent me by e-mail and it built up without any problems. 
So, you don't have to consider the mail I replied you. 
I hope that your research in the future will have good results ^^

**Comment by NiharMasurkar** [comment]
Hey @ChoiWooCheol  I was getting a similar cmake error ~ Could you please email me the ROS Code for this? 
nihar.masurkar96@gmail.com
